name: Deploy App To Server

on:
  push:
    branches:
      - main

env:
  APP_NAME: fast-api-app
  DOCKERHUB_REGISTRY: somex6/fast-api-app
  TAGS: latest


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Login to DockerHub Registry
      #   run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # - name: Deploy Application
      #   run: |
      #     docker build -t $APP_NAME .
      #     docker tag $APP_NAME:$TAGS $DOCKERHUB_REGISTRY:$TAGS
      #     docker push $DOCKERHUB_REGISTRY:$TAGS

      - name: Deploy to App To Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd fastapi-book-project
            git pull
            docker stop fastapi-app-v1
            docker rm fastapi-api-v1
            docker build -t fastapi-app . && docker run -d --name fastapi-app-v1 -p 8000:8000 fastapi-app
