name: Run Pytest

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  APP_NAME: fast-api-app
  DOCKERHUB_REGISTRY: somex6/fast-api-app
  TAGS: latest


jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Deploy Application
        run: |
          docker build -t $APP_NAME .
          docker tag $APP_NAME:$TAGS $DOCKERHUB_REGISTRY:$TAGS
          docker push $DOCKERHUB_REGISTRY:$TAGS

